### ISSUE TITLE
RCTJSONStringify() Encountered

### ISSUE THREAD

**Issue by dr3** [huiseoul/react-native-fit-image#40]
This code works perfectly
`<FitImage
       source={require('./../../images/testimage.jpg')}
       style={styles.fitImageWithSize}
/>`
But this code gets an error
`<FitImage
       source={{ uri: 'http://facebook.github.io/react/img/logo_og.png' }}
       style={styles.fitImageWithSize}
/>`

The error is 
`ExceptionsManager.js:82RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)`

Does this still work, or has react updated and broken it?

**Comment by originerd** [comment]
Hi, @drewmcmillan. Thanks for reporting.

I checked it right now, and I have a same problem as you said about `http://facebook.github.io/react/img/logo_og.png`. But it works other image urls like `https://facebook.github.io/react-native/img/favicon.png` or `https://cdn.huiseoul.com/icon.png`. I don't know why it occurs error about that image at this time.

**Comment by originerd** [comment]
Hi, @drewmcmillan.

I checked it right now, and I have a same problem as you said about `http://facebook.github.io/react/img/logo_og.png`. Because the image url has changed from `http` to `https`, so it failed to get size of that image. If you try again with `https://facebook.github.io/react/img/logo_og.png`, I think it works successfully.

 Thanks for reporting.

**Comment by originerd** [comment]
#39.

Currently, it doesn't work for `http` images.

**Comment by originerd** [comment]
https://github.com/facebook/react-native/issues/8520
