### ISSUE TITLE
source is only working by given url. source: {require('')} is not working

### ISSUE THREAD

**Issue by ArtixZ** [huiseoul/react-native-fit-image#65]

**Comment by sunkibaek** [comment]
There are two reasons RNFI does not support local images:

1. RN itself supports image info on local images
2. Your app will load local images instantly so you do not need functions like showing activity indicator while loading.

That said, I can see the benefit of supporting local images so that you can only use one component for all your images in your source code. I'll consider adding the function in the future.

Thanks!
